service: product-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

plugins:
  - serverless-webpack
package:
  individually: true

functions:
  getProductsList:
    handler: functions/getProductsList/getProductsList.handler
    events:
      - http:
          path: products 
          method: get
          cors: true
    
  getProductsById:
    handler: functions/getProductsById/getProductsById.handler
    events:
      - http:
          path: products/{productId}
          method: get
          cors: true